WIP: Citadel map
orden-gg/ghst-gg pull request #158
Opened 2022-01-10 09:48 UTC by Vladislav94

2022-01-15 12:55 UTC, andkoval commented
@Vladislav94 Please fix all warnings.
<img width="1095" alt="Screenshot 2022-01-15 at 14 54 20" src="https://user-images.githubusercontent.com/42136738/149622411-bc842189-c695-4c6a-8fd8-8750667a93c9.png">

2022-01-17 11:13 UTC, andkoval requested changes

2022-01-17 11:13 UTC, andkoval commented on src/data/guilds.js
> -            '0x17a3831B39cc557296d0C322f9C2D42C0b3A8F3f',
duplicated address

2022-01-17 11:14 UTC, Vladislav94 commented on src/api/thegraph.js
> +        // return await getGraphData(clientFactory.realmClient, parselQuery(id)).then(response => response);
done

2022-01-17 11:14 UTC, Vladislav94 commented on src/components/Citadel/Citadel.js
> +        // return () => controller?.abort(); // cleanup on destroy
done

2022-01-17 11:14 UTC, Vladislav94 commented on src/contexts/ClientContext.js
> +            // setRealm(commonUtils.basicSort(response, filter, dir));
done

2022-01-17 11:23 UTC, andkoval approved these changes

2022-01-17 11:24 UTC, merged