Parcel page
orden-gg/ghst-gg pull request #184
Opened 2022-02-04 22:34 UTC by an-uhryn

2022-02-05 07:36 UTC, andkoval commented
@an-uhryn let's use single-quotes everywhere

2022-02-05 07:42 UTC, andkoval requested changes

2022-02-05 07:42 UTC, andkoval commented on src/api/thegraph.js
> +    listedParcelQuery, getParcelHistoricalPricesQuery
last one :)

2022-02-07 14:28 UTC, an-uhryn commented on src/api/thegraph.js
> +    listedParcelQuery, getParcelHistoricalPricesQuery
Done))

2022-02-07 14:28 UTC, an-uhryn commented
> @an-uhryn let's use single-quotes everywhere

Lets do it)

2022-02-08 07:42 UTC, andkoval approved these changes

2022-02-08 07:42 UTC, merged